# pull official base image
FROM node as tradedesk-build

# set working directory
WORKDIR /app


# install app dependencies
COPY package.json .
RUN npm install


# add app
COPY . .
ENV TRS_API=http://docker6-ma:8016 


EXPOSE 3000
# start app
RUN npm run build

FROM nginx
COPY --from=tradedesk-build /app/dist /usr/share/nginx/html
COPY --from=tradedesk-build /app/nginx.conf /etc/nginx/conf.d/default.conf